name: NodeCI

on: [push]

jobs:
  test:
    name: Test on node ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn --frozen-lockfile --ignore-optional
        env:
          CI: 'true'
      - name: Build
        run: tsc
        env:
          CI: 'true'
      - name: Lint
        run: yarn run lint
        env:
          CI: 'true'
      - name: Test
        run: yarn run test
        env:
          CI: 'true'
